Default: &defaults
  host: "localhost"
  port: 3000
  copyright: # WebToInk (Lorenz & Capistrano) 
  # analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://thlorenz.com/webtoink"
  <<: *defaults
