Default: &defaults
  database: WebToKindle.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: WebToKindle_test.sqlite3
  <<: *defaults

Staging:
  database: WebToKindle_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: WebToKindle_production.sqlite3
  poolsize: 100
  <<: *defaults
