Default: &defaults
  database: WebToInk.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: WebToInk_test.sqlite3
  <<: *defaults

Staging:
  database: WebToInk_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: WebToInk_production.sqlite3
  poolsize: 100
  <<: *defaults
