Default: &defaults
  host: "localhost"
  port: 3000
  copyright: # WebToInk (Lorenz & Capistrano) 
  # analytics: UA-YOURCODE

Development:
  approot: "http://webtoink.thlorenz.com"
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://webtoink.thlorenz.com"
  <<: *defaults
